# **Numpy will help us to work with  the matrices**

In [ ]:
import numpy as np

Array= list where we can store same data type
*  index starts from zero
*  they can be broadcasted



In [ ]:
a=np.array([1,2,3])

type of array

In [ ]:
type(a)

**arange**

In [ ]:
x=np.arange(0,5,0.5)

In [ ]:
x


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

# **Array**
1.  np.zeros
2.   np.ones
1.   np.linspace

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [ ]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**function** **with** **linear** **step**
can give hom many numbers requried

In [ ]:
print(np.linspace(0,100,5))

[  0.  25.  50.  75. 100.]


#**Random** **values**

In [ ]:
np.random.rand(3,2)

array([[0.00456548, 0.06261219],
       [0.64007597, 0.27277491],
       [0.62784887, 0.84395795]])

In [ ]:
np.random.randn(4,2)

array([[-1.86770166, -0.67274467],
       [ 1.2201438 ,  0.22544702],
       [-0.60633315, -0.8010726 ],
       [ 1.27784392, -0.98352506]])

In [ ]:
np.random.randint(0,100,(4,2))

array([[ 5, 27],
       [ 7, 69],
       [68, 42],
       [90, 72]])

#**RESHAPE**
RESHAPE VALUE SHOUD BE SAME N*M

In [ ]:
m=np.random.randint(0,200,(5,50))

In [ ]:
m

array([[145,  93,  76, 101, 138, 113,  30,  10, 136,  61,  63, 132, 154,
         38,  46,  84,  20, 123,  30,  98, 114,  33, 140,  89, 126,  19,
         71,  49, 152, 172, 183, 101, 130, 168, 195,   7,  15, 103, 190,
        130, 103,  16,  66,  85, 126,  68, 115, 198,  32,  82],
       [166,   1, 174,  56,  69,  43,  58, 133,  35, 102, 135,  16,  93,
        108,  84,  87, 167, 103, 144,  86, 113,  87,  64,  44, 138, 153,
         33, 125, 113,  43,   5, 187,   4,   7,  13, 183,  82, 133, 115,
        162,  65,  22, 168,  18, 107,  67, 138,   4, 125, 143],
       [ 23,  73,  30, 137,   8, 139, 165, 108,  17,  46, 174,  64,  42,
         49,  24, 137,   8,  83,  49,  59, 187, 123, 190,  66,  18,  43,
        111,  35, 137,  15, 163,  81,  48, 121,  64, 102, 114, 110,  71,
        163, 191,  55,  68, 191, 105, 171, 189,  78, 132, 106],
       [107,  60, 149,  97, 125, 177, 172,  87, 177, 178, 198, 193, 148,
        123, 123, 184,  26,  97,  87, 100,  32,  36, 177, 146, 136,  98,
     

In [ ]:
m.shape

(5, 50)

In [ ]:
m=m.reshape(5,2,25)
#here we have 4 (2*4 matrices)

In [ ]:
m

array([[[145,  93,  76, 101, 138, 113,  30,  10, 136,  61,  63, 132,
         154,  38,  46,  84,  20, 123,  30,  98, 114,  33, 140,  89,
         126],
        [ 19,  71,  49, 152, 172, 183, 101, 130, 168, 195,   7,  15,
         103, 190, 130, 103,  16,  66,  85, 126,  68, 115, 198,  32,
          82]],

       [[166,   1, 174,  56,  69,  43,  58, 133,  35, 102, 135,  16,
          93, 108,  84,  87, 167, 103, 144,  86, 113,  87,  64,  44,
         138],
        [153,  33, 125, 113,  43,   5, 187,   4,   7,  13, 183,  82,
         133, 115, 162,  65,  22, 168,  18, 107,  67, 138,   4, 125,
         143]],

       [[ 23,  73,  30, 137,   8, 139, 165, 108,  17,  46, 174,  64,
          42,  49,  24, 137,   8,  83,  49,  59, 187, 123, 190,  66,
          18],
        [ 43, 111,  35, 137,  15, 163,  81,  48, 121,  64, 102, 114,
         110,  71, 163, 191,  55,  68, 191, 105, 171, 189,  78, 132,
         106]],

       [[107,  60, 149,  97, 125, 177, 172,  87, 177, 178, 198, 193,
       

# **operations on numpy**

In [ ]:
m

In [ ]:
m.min()

1

In [ ]:
m.max()

198

In [ ]:
m.argmin()
#return the index of the min

51

In [ ]:
m.argmax()

47

In [ ]:
m.sum()

25335

**statistical operations**
mean=sun/n
median= sort and 

In [ ]:
m.mean()

101.34

In [ ]:
np.median(m)

102.0

In [ ]:
a.std()

0.816496580927726

In [ ]:
m+1

array([[[146,  94,  77, 102, 139, 114,  31,  11, 137,  62,  64, 133,
         155,  39,  47,  85,  21, 124,  31,  99, 115,  34, 141,  90,
         127],
        [ 20,  72,  50, 153, 173, 184, 102, 131, 169, 196,   8,  16,
         104, 191, 131, 104,  17,  67,  86, 127,  69, 116, 199,  33,
          83]],

       [[167,   2, 175,  57,  70,  44,  59, 134,  36, 103, 136,  17,
          94, 109,  85,  88, 168, 104, 145,  87, 114,  88,  65,  45,
         139],
        [154,  34, 126, 114,  44,   6, 188,   5,   8,  14, 184,  83,
         134, 116, 163,  66,  23, 169,  19, 108,  68, 139,   5, 126,
         144]],

       [[ 24,  74,  31, 138,   9, 140, 166, 109,  18,  47, 175,  65,
          43,  50,  25, 138,   9,  84,  50,  60, 188, 124, 191,  67,
          19],
        [ 44, 112,  36, 138,  16, 164,  82,  49, 122,  65, 103, 115,
         111,  72, 164, 192,  56,  69, 192, 106, 172, 190,  79, 133,
         107]],

       [[108,  61, 150,  98, 126, 178, 173,  88, 178, 179, 199, 194,
       

In [ ]:
a**2

array([1, 4, 9])

In [ ]:
b=np.array([2,3,4])

In [ ]:
a+b

array([3, 5, 7])

In [ ]:
a*b

array([ 2,  6, 12])

# **matrix** **Maltiplication**

In [ ]:
a,b

(array([1, 2, 3]), array([2, 3, 4]))

In [ ]:
c=np.array([1,5,3])

In [ ]:
c

array([1, 5, 3])

In [ ]:
b

array([2, 3, 4])

In [ ]:
np.dot(a,b)

20

comparisions and logical operations

In [ ]:
c

array([1, 5, 3])

In [ ]:
a==c

array([ True, False,  True])

In [ ]:
a>c

array([False, False, False])

In [ ]:
np.array_equal(a,b)

False

In [ ]:
a=np.array([1,0,0,1],dtype=bool)
b=np.array([1,1,0,1],dtype=bool)
np.logical_and(a,b)

array([ True, False, False,  True])

#   **Broadcasting**


manuplating the matrices with diffrent sizes without making any new matrices

In [ ]:
a=np.random.rand(4,3)
#b=np.random.rand(3)
b=np.random.rand(1,3)
#b=np.random.rand(4)


In [ ]:
a

array([[0.82100652, 0.03223694, 0.44912969],
       [0.04930297, 0.71161313, 0.60419853],
       [0.11945805, 0.13100836, 0.51191404],
       [0.9222421 , 0.87720749, 0.37772059]])

In [ ]:
b

array([[0.18615036, 0.76086243, 0.69514309]])

In [ ]:
print(a+b)

[[1.00715688 0.79309938 1.14427278]
 [0.23545333 1.47247556 1.29934163]
 [0.30560841 0.89187079 1.20705713]
 [1.10839247 1.63806993 1.07286368]]


# **PANDAS**

WE CAN ANALYZE AND VISUVALIZE DATA
pandas has all the sql part

1.   series
2.   DataFrame -multi series




In [ ]:
import pandas as pd


## series
it can have a string or values

In [ ]:
n=pd .Series([1,2,3,'sai','sairam','bommadevara',56,52.36,np.nan,56.58])

In [ ]:
n

0              1
1              2
2              3
3            sai
4         sairam
5    bommadevara
6             56
7          52.36
8            NaN
9          56.58
dtype: object

In [ ]:
x=pd .Series([1,2,3,'sai','sairam','bommadevara',56,52.36,np.nan,56.58],index=['a','b','c','d','e','f','g','h','i','j'])

In [ ]:
x

a              1
b              2
c              3
d            sai
e         sairam
f    bommadevara
g             56
h          52.36
i            NaN
j          56.58
dtype: object

In [ ]:
y=pd.Series([1,2,3,4,5,np.nan])
#because of nan the series become float 

In [ ]:
y

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    NaN
dtype: float64

In [ ]:
z=pd.Series([1,2,3,4,5,'sairam'])
#because of nan the series become 

In [ ]:
z

0         1
1         2
2         3
3         4
4         5
5    sairam
dtype: object

In [ ]:
#dictonary
d={'india':'delhi','usa':"washington Dc",'china':'beijing'}
#series
s=pd.Series(d)

In [ ]:
s['india']

'delhi'

In [ ]:
s.dtype

dtype('O')

# **DataFrame**
dealing with tabular data

In [ ]:
df=pd.DataFrame({'student':['sai','ram','sairam'],'height':[25,30,45],'weight':[70,75,80]})

In [ ]:
df

student  height  weight
0     sai      25      70
1     ram      30      75
2  sairam      45      80

catogorical value list with two catogories

In [ ]:
df=pd.DataFrame({
    'A':pd.Series(1,index=list(range(4)),dtype='float32'),
    'B':np.array([3]*4,dtype='int32'),
    'C':pd.Categorical(['test','train','test','train']),
    'E':'foo'
    })

In [ ]:
 print(pd.Series(1,index=list(range(4)),dtype='float32'))

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float32


In [ ]:
print(np.array([3]*4,dtype='int32'))

[3 3 3 3]


In [ ]:
print(pd.Categorical(['test','train','test','train']))

['test', 'train', 'test', 'train']
Categories (2, object): ['test', 'train']


In [ ]:
df

A  B      C    E
0  1.0  3   test  foo
1  1.0  3  train  foo
2  1.0  3   test  foo
3  1.0  3  train  foo

In [ ]:
df['C']=='test'

0     True
1    False
2     True
3    False
Name: C, dtype: bool

In [ ]:
df[df['C']=='test']

A  B     C    E  test
0  1.0  3  test  foo     9
2  1.0  3  test  foo     6

In [ ]:
df.dtypes

A     float32
B       int32
C    category
E      object
dtype: object

In [ ]:
df.head(2)

A  B      C    E
0  1.0  3   test  foo
1  1.0  3  train  foo

In [ ]:
df.tail(2)

A  B      C    E
2  1.0  3   test  foo
3  1.0  3  train  foo

In [ ]:
df.columns

Index(['A', 'B', 'C', 'E'], dtype='object')

In [ ]:
df.index

NameError: ignored

In [ ]:
df.describe()

A    B
count  4.0  4.0
mean   1.0  3.0
std    0.0  0.0
min    1.0  3.0
25%    1.0  3.0
50%    1.0  3.0
75%    1.0  3.0
max    1.0  3.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   A       4 non-null      float32 
 1   B       4 non-null      int32   
 2   C       4 non-null      category
 3   E       4 non-null      object  
dtypes: category(1), float32(1), int32(1), object(1)
memory usage: 196.0+ bytes


# **manuplating the data with rows and columns**


In [ ]:
df['A']

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float32

In [ ]:
df[['A','E']]
#passing list in the DataFrame

A    E
0  1.0  foo
1  1.0  foo
2  1.0  foo
3  1.0  foo

In [ ]:
#create column
df['test']=[9,5,6,4]

In [ ]:
df

A  B      C    E  test
0  1.0  3   test  foo     9
1  1.0  3  train  foo     5
2  1.0  3   test  foo     6
3  1.0  3  train  foo     4

In [ ]:
df.drop(['test'],axis=1,inplace=True)
#axis for column=1 and row=0
#inplace will make permanent drop

A  B      C    E
0  1.0  3   test  foo
1  1.0  3  train  foo
2  1.0  3   test  foo
3  1.0  3  train  foo

row selection

In [ ]:
df[2:3]
#using slicing in DF

A  B     C    E  test
2  1.0  3  test  foo     6

In [ ]:
df.iloc[3]
# index and location

A           1
B           3
C       train
E         foo
test        4
Name: 3, dtype: object

In [ ]:
df.iloc[2:4,0:2]
#partitioning the data

A  B
2  1.0  3
3  1.0  3

In [ ]:
df.loc()

In [ ]:
df[df['C']=='test']
#row selection

A  B     C    E  test
0  1.0  3  test  foo     9
2  1.0  3  test  foo     6

In [ ]:
df[df['B']>0]

A  B      C    E  test
0  1.0  3   test  foo     9
1  1.0  3  train  foo     5
2  1.0  3   test  foo     6
3  1.0  3  train  foo     4

In [ ]:
TA

## **MISSING** **DATA** and **manuplation**

In [ ]:
df2=df
#shallow copy (changes will automatically chag edf also)

In [ ]:
df2=df.copy() 

In [ ]:
df=df.append({'A':2.0,'B':2.0,'E':"foo"},ignore_index=True)

In [ ]:
df

A    B      C    E  test
0  1.0  3.0   test  foo   9.0
1  1.0  3.0  train  foo   5.0
2  1.0  3.0   test  foo   6.0
3  1.0  3.0  train  foo   4.0
4  2.0  2.0    foo  NaN   NaN
5  2.0  2.0    NaN  foo   NaN

In [ ]:
df.dropna(how='all')

A    B      C    E  test
0  1.0  3.0   test  foo   9.0
1  1.0  3.0  train  foo   5.0
2  1.0  3.0   test  foo   6.0
3  1.0  3.0  train  foo   4.0
4  2.0  2.0    foo  NaN   NaN
5  2.0  2.0    NaN  foo   NaN

In [ ]:
df.dropna(how='any')

A    B      C    E  test
0  1.0  3.0   test  foo   9.0
1  1.0  3.0  train  foo   5.0
2  1.0  3.0   test  foo   6.0
3  1.0  3.0  train  foo   4.0

In [ ]:
df.dropna(axis=1)

A    B
0  1.0  3.0
1  1.0  3.0
2  1.0  3.0
3  1.0  3.0
4  2.0  2.0
5  2.0  2.0

In [ ]:
df.fillna(value=5)

A    B      C    E  test
0  1.0  3.0   test  foo   9.0
1  1.0  3.0  train  foo   5.0
2  1.0  3.0   test  foo   6.0
3  1.0  3.0  train  foo   4.0
4  2.0  2.0    foo    5   5.0
5  2.0  2.0      5  foo   5.0

In [ ]:
df['C']=df['C'].fillna(3)

In [ ]:
df

A    B      C    E  test
0  1.0  3.0   test  foo   9.0
1  1.0  3.0  train  foo   5.0
2  1.0  3.0   test  foo   6.0
3  1.0  3.0  train  foo   4.0
4  2.0  2.0    foo  NaN   NaN
5  2.0  2.0      3  foo   NaN

In [ ]:
df.isna()


A      B      C      E   test
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False   True   True
5  False  False  False  False   True

In [ ]:
df.isna().sum()

A       0
B       0
C       0
E       1
test    2
dtype: int64

# **Groupby**

In [ ]:
df


A    B      C    E  test
0  1.0  3.0   test  foo   9.0
1  1.0  3.0  train  foo   5.0
2  1.0  3.0   test  foo   6.0
3  1.0  3.0  train  foo   4.0
4  2.0  2.0    foo  NaN   NaN
5  2.0  2.0      3  foo   NaN

In [ ]:
df.groupby('test').mean()

A    B
test          
4.0   1.0  3.0
5.0   1.0  3.0
6.0   1.0  3.0
9.0   1.0  3.0

In [ ]:
df.groupby('test').min()

A    B      C    E
test                      
4.0   1.0  3.0  train  foo
5.0   1.0  3.0  train  foo
6.0   1.0  3.0   test  foo
9.0   1.0  3.0   test  foo

In [ ]:
df.groupby('test').max()

A    B      C    E
test                      
4.0   1.0  3.0  train  foo
5.0   1.0  3.0  train  foo
6.0   1.0  3.0   test  foo
9.0   1.0  3.0   test  foo

In [ ]:
df.groupby('test').describe()

A                               ...    B                             
     count mean std  min  25%  50%  75%  ... mean std  min  25%  50%  75%  max
test                                     ...                                  
4.0    1.0  1.0 NaN  1.0  1.0  1.0  1.0  ...  3.0 NaN  3.0  3.0  3.0  3.0  3.0
5.0    1.0  1.0 NaN  1.0  1.0  1.0  1.0  ...  3.0 NaN  3.0  3.0  3.0  3.0  3.0
6.0    1.0  1.0 NaN  1.0  1.0  1.0  1.0  ...  3.0 NaN  3.0  3.0  3.0  3.0  3.0
9.0    1.0  1.0 NaN  1.0  1.0  1.0  1.0  ...  3.0 NaN  3.0  3.0  3.0  3.0  3.0

[4 rows x 16 columns]

# **Data Input and Output**

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('C:\\Users\\sairam\\Downloads\\titanic_data.csv')

FileNotFoundError: ignored